Detailed publishing
proxytranslation/user-docs pull request #45
Opened 2022-03-04 15:06 UTC by Hootyoo

Added step-by-step publishing guides for

- CloudFront
- CloudFlare
- nginx

2022-03-07 14:00 UTC, zmeggyesi requested changes
This really ought to be added to one of the TOC files as well, I had quite a hard time finding it initially.

2022-03-08 12:20 UTC, Hootyoo commented on dashboard2/publishwebsite/integration-guide/cloudfront.md
> +- Your white label is app.translationproxy.com
I was trying to come up with one that's sooo generic that I didn't expect anyone to have it. Would `app.proxytranslation.com` be suitable?

2022-03-08 12:20 UTC, Hootyoo commented on dashboard2/publishwebsite/integration-guide/cloudfront.md
> +9. On *Behaviors*, (which should really be spelled Behavio**u**rs, my spellchecker is complaining)
No fun allowed. Comment is removed.

2022-03-08 14:36 UTC, Hootyoo commented on dashboard2/publishwebsite/integration-guide/nginx.md
> +```
I didn't even mention `apt dist-upgrade` or `do-release-update`... In any case, I removed these lines.

2022-03-08 14:39 UTC, zmeggyesi commented on dashboard2/publishwebsite/integration-guide/cloudfront.md
> +- Your white label is app.translationproxy.com
Yes, that would work.

2022-03-08 14:43 UTC, zmeggyesi approved these changes

2022-03-08 14:43 UTC, zmeggyesi commented on dashboard2/publishwebsite/integration-guide/nginx.md
> +This should print that the status code is `200`. If it doesn't, a likely explanation is that your server is missing Certificate Authority certificates and as a result can't connect to our service via
This is pretty good!

2022-03-08 14:44 UTC, merged