re-worded the crest guide and some smaller layout fixes
proxytranslation/user-docs pull request #51
Opened 2022-07-22 14:59 UTC by Hootyoo

2022-07-25 13:02 UTC, zmeggyesi requested changes

2022-07-25 13:02 UTC, zmeggyesi commented on index.rst
> +   cookbook/sitesearch
Should these be given a separate section in the index? The way they are now, they kinda blend together with the rest of the content...

2022-07-26 08:38 UTC, zmeggyesi commented on dashboard2/publishwebsite/clientsidetranslation.md
> +There are three things you must do on the Dashboard. First, head to the _Export_ section. Under _File format_, select _Client side translation (JS, export only). The rest of the options change to the
Agreed.

2022-08-05 12:01 UTC, zmeggyesi requested changes
Something's still "off" about the cookbook index...

2022-08-05 12:01 UTC, zmeggyesi commented on cookbook/index.rst
> +sitesearch
![image](https://user-images.githubusercontent.com/16238446/183073188-dbb0de06-7c16-42c1-9d5e-bb8cc3a7390c.png)
Something's fucky...

2022-08-08 10:36 UTC, Hootyoo commented
Kriszta said she had a few comments as well. She has a meeting with Balázs later this week to prioritise her tasks. We agreed to wait until then and work on her feedback before releasing this branch.

2022-08-08 10:37 UTC, Hootyoo commented on dashboard2/publishwebsite/clientsidetranslation.md
> +There are three things you must do on the Dashboard. First, head to the _Export_ section. Under _File format_, select _Client side translation (JS, export only). The rest of the options change to the
[Trello card](https://trello.com/c/JECx8GVh/4899-standardise-spelling-of-hyphenated-names) created.

2022-08-08 10:39 UTC, zmeggyesi approved these changes

2022-08-08 10:39 UTC, merged